fixed some error with commands and implemented add command

diff --git a/savedots b/savedots
--- a/savedots
+++ b/savedots
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -e
+
 if [ "$1" = "help" ]; then 
   echo "savedots [command]"
   echo "  init     inits the repo"
@@ -22,18 +24,20 @@ if ! command -v git &> /dev/null; then
   exit 1
 fi
 
+configfile="$HOME/.config/savedots.json"
+
 if [ "$1" = "cp" ]; then
   if [ ! -f savedots.json ]; then
     echo "savedots.json not found"
     exit 1
   fi
-  if [ -f savedots.json ]; then
-    read -p "file $path already exists, wanna override it? [Y/n]: " -r
+  if [ -f $configfile ]; then
+    read -p "file $configfile already exists, wanna override it? [Y/n]: " -r
     if [[ ! $REPLY =~ ^[Yy]{0,1}$ ]]; then
       exit 1
     fi 
   fi
-  cp savedots.json $HOME/.config/savedots.json
+  cp savedots.json $configfile
   files=$(jq ".files" savedots.json)
   LEN=$(echo $files | jq '. | length')
   for (( i=0; i<$LEN; i++ )); do
@@ -53,19 +57,31 @@ if [ "$1" = "cp" ]; then
     echo copied $name $path
   done
   exit 0
-fi
-
-configfile="$HOME/.config/savedots.json"
-if [ ! -f "$configfile" ]; then
-  echo "$configfile not found"
-  exit 1
-fi
+fi 
 
 cachedir=$HOME/.cache/savedots
-repo=$(jq -r '.remoterepo' $configfile)
 
 if [ "$1" = "init" ]; then
-  if [ ! -d "$cachedir" ]; then
+  repo=$2
+  if [ ! $repo ]; then
+    read -p "repo: " repo
+  fi
+  if git ls-remote --exit-code $repo > /dev/null 2>&1; then
+    rm -rf $cachedir
+    git clone $repo $cachedir
+    if [ ! -f $cachedir/savedots.json ]; then
+      echo "savedots.json not found"
+      exit 1
+    fi
+    if [ -f $configfile ]; then
+      read -p "file $configfile already exists, wanna override it? [Y/n]: " -r
+      if [[ ! $REPLY =~ ^[Yy]{0,1}$ ]]; then
+        exit 1
+      fi 
+    fi
+    cp $cachedir/savedots.json $configfile
+  else
+    "{\"remoterepo\": \"$repo\", "files": []}" > $configfile
     mkdir $cachedir
     cd $cachedir
     git init
@@ -76,19 +92,51 @@ if [ "$1" = "init" ]; then
     cd $cachedir
     git add .
     git commit -m "start"
-  else
-    echo savedots already inited
+  fi
+  exit 0
+fi
+
+if [ ! -f "$configfile" ]; then
+  echo "$configfile not found"
+  exit 1
+fi
+
+repo=$(jq -r '.remoterepo' $configfile)
+if [ ! "$repo" ]; then
+  echo no remoterepo specified
+  exit 1
+fi
+
+if [ ! -d "$cachedir" ]; then
+  if ! git ls-remote --exit-code $repo > /dev/null 2>&1; then
+    echo $repo does not exists or is empty
+    echo try running $0 init
     exit 1
   fi
-else
-  if [ ! -d "$cachedir" ]; then
-    if ! git ls-remote --exit-code $repo > /dev/null 2>&1; then
-      echo $repo does not exists or is empty
-      echo try running $0 init
-      exit 1
-    fi
-    git clone --depth=1 $repo $cachedir
+  git clone --depth=1 $repo $cachedir
+fi
+
+if [ "$1" = "add" ]; then
+  path=$2
+  name=$3
+  if [ ! "$path" ]; then
+    read -p "path: " path
   fi
+  if [ ! "$name" ]; then
+    read -p "name: " name
+  fi
+  
+  obj="{\"name\": \"$name\",\"path\": \"${path/$HOME/\~}\"}"
+
+  if [ ! $(jq ".files | index($obj)" $configfile) = null ]; then
+    echo $name $path already added
+    exit 1
+  fi
+
+  temp=$(mktemp)
+  jq ".files += [$obj]" $configfile > $temp
+  cp $temp $configfile
+  exit 0
 fi
 
 jq -c ".files.[]" $configfile | while read i; do
@@ -109,13 +157,14 @@ if [ ! -f $file ] || ! git diff $file $path; then
 fi
 done
 
-if ! git diff $configfile $cachedir/savedot.json; then
-  cp $configfile $cachedir/savedot.json
-  git add $cachedir/savedot.json
+if ! git diff $configfile $cachedir/savedots.json; then
+  cp $configfile $cachedir/savedots.json
+  git add $cachedir/savedots.json
 fi
 
 cd $cachedir
 if [[ `git status --porcelain` ]]; then
+  echo "asd"
   git commit -m $(date +%F:%T)
   git push -u origin master
 fi
